#pragma once

// Generated by Tools/ArtPipeline/build_all.py - do not edit by hand.
// The block art vocabulary: footprints are in grid units, 4 per road cell.
// kind: 0 house, 1 office, 2 prop, 3 composite. street props belong on a kerb.
namespace td::art
{
	struct BlockItem { const char* id; int kind; int fw; int fh; bool street; };
	inline const BlockItem kBlockItems[] = {
		{ "house_brick_red", 0, 3, 3, false },
		{ "house_brick_dormer", 0, 3, 3, false },
		{ "house_cream_blue", 0, 3, 3, false },
		{ "house_terracotta", 0, 3, 3, false },
		{ "house_half_timber", 0, 3, 3, false },
		{ "house_narrow_tall", 0, 2, 3, false },
		{ "house_stone_shutters", 0, 4, 3, false },
		{ "house_shop_awning", 0, 4, 3, false },
		{ "house_cafe_terrace", 0, 4, 3, false },
		{ "house_bakery", 0, 3, 4, false },
		{ "house_townhouse_pair", 0, 6, 3, false },
		{ "house_row_long", 0, 9, 3, false },
		{ "house_corner_bay", 0, 5, 5, false },
		{ "house_villa_garden", 0, 5, 4, false },
		{ "office_glass_chip", 1, 5, 5, false },
		{ "office_loft_startup", 1, 7, 5, false },
		{ "office_classic_columns", 1, 5, 5, false },
		{ "office_tech_cube", 1, 6, 6, false },
		{ "tree_big", 2, 2, 2, false },
		{ "tree_small", 2, 1, 1, false },
		{ "tree_pine", 2, 2, 2, false },
		{ "bush_round", 2, 1, 1, false },
		{ "hedge_segment", 2, 1, 1, false },
		{ "fence_segment", 2, 1, 1, false },
		{ "flowerbed", 2, 2, 1, false },
		{ "bench", 2, 2, 1, false },
		{ "lamp_post", 2, 1, 1, true },
		{ "trash_bin", 2, 1, 1, true },
		{ "planter_box", 2, 1, 1, false },
		{ "phone_booth", 2, 1, 1, true },
		{ "bicycle_rack", 2, 2, 1, true },
		{ "kiosk_hex", 2, 3, 3, true },
		{ "kiosk_rect", 2, 3, 2, true },
		{ "bus_stop", 2, 3, 2, true },
		{ "pergola", 2, 3, 2, false },
		{ "playground", 2, 4, 4, false },
		{ "statue_pedestal", 2, 2, 2, false },
		{ "fountain_park", 2, 4, 4, false },
		{ "parasol_tables", 2, 2, 2, false },
		{ "plaza_fountain", 3, 6, 6, false },
		{ "market_stalls", 3, 7, 5, false },
		{ "dog_park", 3, 6, 5, false },
		{ "community_garden", 3, 5, 5, false },
	};
}
